#!/bin/bash

if [[ "$1" == "0000000000000000000000000000000000000000" ]]; then
	basePath="$HOME/dev/sites/christianerben-eu"
	paths=(.env)

	for path in "${paths[@]}"; do
		cp "$basePath/$path" "$(pwd)/$path"
	done
fi
