import { readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";

const generatedPaths = [
  "public/llms.txt",
  "public/sitemap.xml",
  "src/content/content.ts",
];

// generate:cv output is not byte-deterministic (embedded timestamps), so the
// tracked binaries are checked against stable invariants instead of
// regenerated bytes. Byte freshness remains a release step: the pre-commit
// hook regenerates them on `development`.
const expectedCvArtifacts = [
  "public/cv/christian_erben_cv_en.pdf",
  "public/cv/christian_erben_cv_en_with_certificates.pdf",
  "public/cv/christian_erben_cv_en.docx",
  "public/cv/christian_erben_cv_de.pdf",
  "public/cv/christian_erben_cv_de_with_certificates.pdf",
  "public/cv/christian_erben_cv_de.docx",
];

const PDF_SIGNATURE = Buffer.from("%PDF");
const ZIP_SIGNATURE = Buffer.from([0x50, 0x4b, 0x03, 0x04]);

class CommandFailedError extends Error {
  constructor(
    command: string,
    args: string[],
    readonly status: number,
  ) {
    super(`Command failed: ${command} ${args.join(" ")}`);
  }
}

function run(command: string, args: string[]) {
  const result = spawnSync(command, args, {
    cwd: process.cwd(),
    encoding: "utf8",
    stdio: "inherit",
  });

  if (result.status !== 0) {
    throw new CommandFailedError(command, args, result.status ?? 1);
  }
}

function listTrackedFiles(paths: string[]) {
  const result = spawnSync("git", ["ls-files", "--", ...paths], {
    cwd: process.cwd(),
    encoding: "utf8",
    stdio: "pipe",
  });

  if (result.status !== 0) {
    throw new Error(result.stderr.trim() || "Failed to list generated files.");
  }

  return result.stdout.split("\n").filter(Boolean);
}

async function captureTrackedFiles() {
  return await Promise.all(
    listTrackedFiles(generatedPaths).map(async (file) => ({
      file,
      content: await readFile(file),
    })),
  );
}

async function verifyCvArtifacts() {
  const tracked = new Set(listTrackedFiles(expectedCvArtifacts));
  const problems: string[] = [];

  for (const file of expectedCvArtifacts) {
    if (!tracked.has(file)) {
      problems.push(`${file} (not tracked in git)`);
      continue;
    }

    let content: Buffer;
    try {
      content = await readFile(file);
    } catch {
      problems.push(`${file} (missing on disk)`);
      continue;
    }

    const signature = file.endsWith(".pdf") ? PDF_SIGNATURE : ZIP_SIGNATURE;
    if (!content.subarray(0, signature.length).equals(signature)) {
      problems.push(`${file} (empty or invalid file signature)`);
    }
  }

  return problems;
}

async function restoreFiles(snapshot: Array<{ file: string; content: Buffer }>) {
  await Promise.all(
    snapshot.map(async ({ file, content }) => {
      await writeFile(file, content);
    }),
  );

  const tracked = new Set(snapshot.map(({ file }) => file));
  const untracked = spawnSync(
    "git",
    ["ls-files", "--others", "--exclude-standard", "--", ...generatedPaths],
    {
      cwd: process.cwd(),
      encoding: "utf8",
      stdio: "pipe",
    },
  );

  if (untracked.status !== 0) {
    return;
  }

  await Promise.all(
    untracked.stdout
      .split("\n")
      .filter((file) => file && !tracked.has(file))
      .map((file) => rm(file, { force: true })),
  );
}

async function listChangedGeneratedFiles(snapshot: Array<{ file: string; content: Buffer }>) {
  const changedFiles: string[] = [];

  for (const { file, content } of snapshot) {
    const current = await readFile(file);
    if (!content.equals(current)) {
      changedFiles.push(file);
    }
  }

  return changedFiles;
}

async function main() {
  const cvProblems = await verifyCvArtifacts();
  if (cvProblems.length > 0) {
    console.error(
      "Tracked CV artifacts failed verification. Run `bun run generate:cv` and commit the results:",
    );
    for (const problem of cvProblems) {
      console.error(` - ${problem}`);
    }
    process.exit(1);
  }

  const snapshot = await captureTrackedFiles();

  try {
    run("bun", ["run", "generate:llms"]);
    run("bun", ["run", "generate:sitemap"]);
    run("bun", ["run", "update:last-updated"]);
  } catch (error) {
    await restoreFiles(snapshot);
    throw error;
  }

  const changedFiles = await listChangedGeneratedFiles(snapshot);
  if (changedFiles.length === 0) {
    console.log("Generated artifacts are current.");
    return;
  }

  await restoreFiles(snapshot);
  console.error("Generated artifacts are stale. Run the generator commands and commit the results:");
  for (const file of changedFiles) {
    console.error(` - ${file}`);
  }
  process.exit(1);
}

main().catch((error) => {
  if (error instanceof CommandFailedError) {
    process.exit(error.status);
  }

  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
